apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: elk
  labels:
    app: elasticsearch
    role: master
spec:
  selector:
    app: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
