apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app: elasticsearch
    role: client
spec:
  selector:
    app: elasticsearch
    role: client
  type: NodePort  
  ports:
  - name: http
    port: 9200
  - name: tcp
    port: 9300
#type: LoadBalancer
