apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: elk
  labels:
    app: fluentd-es
spec:
  selector:
    app: fluentd-es
  type: NodePort  
  ports:
  - name: http
    port: 9880
  - name: forward
    port: 24224

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-es-v2.4.0
  namespace: elk
  labels:
    app: fluentd-es
spec:
  selector:
    matchLabels:
      app: fluentd-es
  template:
    metadata:
      labels:
        app: fluentd-es
    spec:
      containers:  
      - name: fluentd-es
        image: mirrorgooglecontainers/fluentd-elasticsearch:v2.4.0
        ports:
        - containerPort: 9880
          name: http
        - containerPort: 24224
          name: forward
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      #nodeSelector:
        #beta.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-es-config-v0.2.0