apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
