# 集成开始环境部署包括了mongodb,redis,rabbitmq,mysql等
version: "3.3"
services:

 Redis:
  image: sameersbn/redis:latest
  ports:
    - "6379:6379"
  volumes:
    - redis_data:/var/lib/redis:Z
  restart: always

 PostgreSQL:
  restart: always
  image: sameersbn/postgresql:9.6-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - DB_USER=wang
    - DB_PASS=yunfei
    - DB_NAME=order
  volumes:
    - postgresql_data:/var/lib/postgresql:Z 

networks:
  dev:
    driver: bridge

volumes:
  redis_data:
  postgresql_data:
