# 集成开始环境部署包括了mongodb,redis,rabbitmq,mysql等
version: "3.3"
services:

 Redis:
  image: sameersbn/redis:latest
  ports:
    - "6379:6379"
  volumes:
    - redis_data:/var/lib/redis
  restart: always

 mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  dev:
    driver: bridge

volumes:
  redis_data:
  mysql_data:
